services:
  cache:
    container_name: cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - ${CACHE_PORT}:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${CACHE_PWD}
    volumes:
      - cache:/data
    networks:
      - go-base

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
      POSTGRES_HOST: ${PG_HOST}
      POSTGRES_DB: ${PG_DB}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - ${PG_PORT}:5432
    networks:
      - go-base
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgpool:
  #   container_name: pgpool
  #   image: pgpool/pgpool:latest
  #   restart: always
  #   env_file: .env
  #   environment:
  #     - PGPOOL_BACKEND_NODES=0:postgres:5432
  #     - PGPOOL_SR_CHECK_USER=${PG_USER}
  #     - PGPOOL_SR_CHECK_PASSWORD=${PG_PWD}
  #     - PGPOOL_ENABLE_LDAP=no
  #     - PGPOOL_POSTGRES_USERNAME=${PG_USER}
  #     - PGPOOL_POSTGRES_PASSWORD=${PG_PWD}
  #     - PGPOOL_ADMIN_USERNAME=${PGPOOL_ADMIN_USER:-admin}
  #     - PGPOOL_ADMIN_PASSWORD=${PGPOOL_ADMIN_PWD:-adminpassword}
  #     - PGPOOL_ENABLE_LOAD_BALANCING=yes
  #     - PGPOOL_MAX_POOL=15
  #     - PGPOOL_CHILD_LIFE_TIME=300
  #     - PGPOOL_CONNECTION_LIFE_TIME=0
  #     - PGPOOL_CLIENT_IDLE_LIMIT=0
  #   ports:
  #     - ${PGPOOL_PORT:-5433}:5432
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - go-base
  #   healthcheck:
  #     test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    networks:
      - go-base
    ports:
      - ${RMQ_PORT}:5672
      - ${RMQ_UI_PORT}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PWD}

networks:
  go-base:
    driver: bridge

volumes:
  cache:
    driver: local
  postgres:
    driver: local
