services:
  cache:
    container_name: cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - ${CACHE_PORT}:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${CACHE_PWD}
    volumes:
      - cache:/data
    networks:
      - gobase

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
      POSTGRES_HOST: ${PG_HOST}
      POSTGRES_DB: ${PG_DB}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - ${PG_PORT}:5432
    networks:
      - gobase

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    networks:
      - gobase
    ports:
      - ${RMQ_PORT}:5672
      - ${RMQ_UI_PORT}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PWD}

networks:
  gobase:
    driver: bridge

volumes:
  cache:
    driver: local
  postgres:
    driver: local
