x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:
  # ********************
  # Telemetry Components
  # ********************
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    command:
      - "--memory.max-traces"
      - "10000"
      - "--query.base-path"
      - "/jaeger/ui"
      - "--prometheus.server-url"
      - "http://prometheus:9090"
      - "--query.ui-config=/etc/jaeger-ui.json"
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
    ports:
      - "${JAEGER_PORT}:${JAEGER_PORT}" # Jaeger UI
      - "4317" # OTLP gRPC default port
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
    logging: *logging
    volumes:
      - ./config/jaeger-ui.json:/etc/jaeger-ui.json

  # Grafana
  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    deploy:
      resources:
        limits:
          memory: 150M
    volumes:
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "${GRAFANA_PORT}:3000"
    logging: *logging

  # OpenTelemetry Collector
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.133.0
    container_name: otelcol
    deploy:
      resources:
        limits:
          memory: 125M
    restart: unless-stopped
    command: ["--config=/etc/otelcol-config.yml"]
    volumes:
      - ./config/otelcol-config.yml:/etc/otelcol-config.yml
    ports:
      - "${OTL_RPC}:4317" # OTLP over gRPC receiver
      - "${OTL_HTTP}:4318" # OTLP over HTTP receiver
      - "${OTL_BROWSER}:55679" # Browser
      - "${OTL_HEALTH}:13133" # Heath
      - "9464:9464" # Prometheus exporter
      - "8888:8888" # metrics endpoint (collector self-telemetry)
    depends_on:
      - jaeger
    logging: *logging

  # Prometheus
  prometheus:
    image: quay.io/prometheus/prometheus:v2.46.0
    container_name: prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --enable-feature=exemplar-storage
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    deploy:
      resources:
        limits:
          memory: 300M
    ports:
      - "${PROMETHEUS_PORT}:9090"
    logging: *logging
