receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

processors:
  batch:
  transform:
    trace_statements:
      - context: span
        statements:
          - delete_key(resource.attributes, "process.command_args")
          - truncate_all(attributes, 4095)
          - truncate_all(resource.attributes, 4095)
    log_statements:
      - context: log
        statements:
          - delete_key(resource.attributes, "process.command_args")
          - truncate_all(attributes, 4095)
          - truncate_all(resource.attributes, 4095)
    metric_statements:
      - context: metric
        statements:
          - delete_key(resource.attributes, "process.command_args")
          - set(description, "Measures the duration of inbound HTTP requests") where name == "http.server.duration"
  filter:
    metrics:
      exclude:
        match_type: strict
        metric_names:
          - queueSize

exporters:
  debug:
    verbosity: detailed

extensions:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
